# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Koupleless Runtime Snapshot

## https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release
## trigger manually
on:
  workflow_dispatch:

jobs:
#  build_and_test:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v3
#      - name: Set up JDK 8
#        uses: actions/setup-java@v3
#        with:
#          java-version: '8'
#          distribution: 'temurin'
#          cache: maven
#
#      - name: Update Maven version to 3.9.x to enable cross bundle without install
#        env:
#          MAVEN_VERSION: '3.9.5'
#        run: |
#          wget https://archive.apache.org/dist/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz
#          tar xzvf apache-maven-${MAVEN_VERSION}-bin.tar.gz
#          echo "MAVEN_HOME=$GITHUB_WORKSPACE/apache-maven-${MAVEN_VERSION}" >> $GITHUB_ENV
#          echo "$GITHUB_WORKSPACE/apache-maven-${MAVEN_VERSION}/bin" >> $GITHUB_PATH
#
#      - name: Build with Maven
#        run: mvn clean install -DskipTests -B -U -e && sh ./check_format.sh
#
#      - name: Checkout adapter Repository
#        uses: actions/checkout@v3
#        with:
#          repository: 'koupleless/adapter'
#          path: 'adapter'
#
#      - name: Build adapter and install
#        run: cd adapter && ./script/ci_build.sh 1.8 install
#
#      - name: Set up Docker
#        uses: docker/metadata-action@v3
#        with:
#          images: |
#            node:14
#
#      - name: Checkout sampletest Repository
#        uses: actions/checkout@v3
#        with:
#          repository: 'koupleless/samples'
#          path: 'samples'
#
#      - name: get sofa-runtime version & update sofa-runtime version for all test sample app
#        run: |
#          koupleless_runtime_version=$(find koupleless-common -name "*.jar" |grep -v source |sed "s/.*koupleless-common-\(.*\).jar/\1/")
#          echo "升级 koupleless-runtime version to $koupleless_runtime_version"
#          for testsample in `find samples -name "*[^3|^dubbo|^dubbo32]-samples"`;do  sed -i "s/<koupleless.runtime.version>.*<\/koupleless.runtime.version>/<koupleless.runtime.version>$koupleless_runtime_version<\/koupleless.runtime.version>/g"  $testsample/pom.xml ;done
#          for testsample in `find samples -name "*[^3|^dubbo|^dubbo32]-samples"`;do if cat $testsample/pom.xml |grep "<koupleless.runtime.version>"|grep $koupleless_runtime_version;then echo "版本校验通过";else echo "版本校验失败";exit 1;fi;done
#
#      - name: Test Env prepare
#        run: |
#          sudo apt-get update >>/tmp/envprepare.out
#          sudo apt-get install -y expect >>/tmp/envprepare.out
#          docker pull mongo:7.0.2-jammy
#          docker run --name mongodb -d -p 27017:27017 -v /home/runner/work/data:/data/db mongo:7.0.2-jammy
#          docker pull zookeeper:3.9.0
#          docker run -p 2181:2181 -it --name zookeeper --restart always -d zookeeper:3.9.0
#          docker pull apache/rocketmq:4.9.7
#          docker run -d -p 9876:9876 -p 10909:10909 -p 10910:10910 -p 10911:10911 -p 10912:10912 -v $(pwd)/samples/springboot-samples/msg/rocketmq/config/start.sh:/home/rocketmq/rocketmq-4.9.7/bin/start.sh -v $(pwd)/samples/springboot-samples/msg/rocketmq/config/broker.conf:/home/rocketmq/rocketmq-4.9.7/bin/broker.conf apache/rocketmq:4.9.7 sh /home/rocketmq/rocketmq-4.9.7/bin/start.sh
#          docker run -d -p 9092:9092 -p 9093:9093 --name kafka-3.6.2 -e KAFKA_ENABLE_KRAFT=yes -e KAFKA_CFG_NODE_ID=1 -e KAFKA_CFG_PROCESS_ROLES=controller,broker -e KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093 -e KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092 -e KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT -e KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@localhost:9093 -e KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER -e KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv -e ALLOW_PLAINTEXT_LISTENER=yes -e KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true -e KAFKA_BROKER_ID=1 bitnami/kafka:3.6.2
#          sudo apt-get install redis-server -y
#          sudo systemctl start redis-server
#          docker-compose  -f samples/springboot-samples/config/apollo/config/docker-compose.yml up -d
#          sudo cp .github/workflows/ccbin/arkctl /usr/bin/arkctl
#          sudo chmod +x /usr/bin/arkctl
#
#      - name: Run jdk8 koupleless runtime test
#        run: |
#          set -e
#          bash -x .github/workflows/ccbin/start.sh jdk8

  runtime_release_for_jdk8:
#    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }} # Value of the GPG private key to import
          gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase
      - name: Build with Maven
        run: mvn --batch-mode deploy -DskipTests -Psnapshot
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}

  adapter_release_for_jdk8:
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'koupleless/adapter'
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }} # Value of the GPG private key to import
          gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase
      - name: Build with Maven
        run: ./script/ci_build.sh 1.8 snapshot
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
